repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict

-   repo: local
    hooks:
    -   id: remove-multiple-empty-lines
        name: Remove multiple empty lines
        entry: bash -c 'for file in "$@"; do sed -i "" -e :a -e "/^\n*$/{$d;N;ba" -e "}" "$file"; done' --
        language: system
        types: [text]
